[package]
name = "motex"
version = "0.1.0"
authors = ["Parker Burnett <jpburnett@byu.net>"]
edition = "2024"
rust-version = "1.91"
publish = false
readme = "README.md"

[[bin]]
name = "motex"
path = "src/main.rs"

[dependencies]
# N64 texture codec library
pigment64 = "0.4.5"

# GUI framework
gpui = "*"
gpui-component = "0.4.0-preview1"

# Logging
log = "0.4"
env_logger = "0.11"
anyhow = "1.0.100"

# File dialog
rfd = "0.15.4"
