[package]
name = "motex"
version = "0.1.0"
authors = ["Parker Burnett <jpburnett@byu.net>"]
edition = "2024"
rust-version = "1.90"
publish = false
readme = "README.md"

[dependencies]
eframe = { version = "0.30.0", features = ["persistence"] }
egui_extras = { version = "0.30.0" , features = ["all_loaders"]}
anyhow = "1.0.95"
rfd = "0.15.2"
pigment64 = "0.4.5"
strum = "0.26.3"
open = "5.3.2"